import { useRouter } from "next/router";
import { useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { Btn, Card, Field, Notice, Shell } from "./ui";

export function Studio() {
  const router = useRouter();
  const [notice, setNotice] = useState("");
  const [noticeTone, setNoticeTone] = useState<"green" | "amber" | "red">("green");
  const [accountId, setAccountId] = useState("chezahub");
  const [caption, setCaption] = useState(
    "One of the best PS5 adventures just got cheaper. Shop the best active region at chezahub.co.ke.",
  );
  const [image, setImage] = useState<File | null>(null);
  const [preview, setPreview] = useState("");
  const [publishFacebook, setPublishFacebook] = useState(true);
  const [publishInstagram, setPublishInstagram] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [publishing, setPublishing] = useState(false);

  function chooseImage(file: File | null) {
    if (preview) URL.revokeObjectURL(preview);
    setImage(file);
    setPreview(file ? URL.createObjectURL(file) : "");
  }

  async function toDataUrl(file: File) {
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result || ""));
      reader.onerror = () => reject(new Error("Could not read the image."));
      reader.readAsDataURL(file);
    });
  }

  async function generateCaption() {
    if (!image) {
      setNoticeTone("amber");
      setNotice("Add a PNG, JPG or WEBP image before generating a caption.");
      return;
    }
    setGenerating(true);
    setNotice("");
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ imageBase64: await toDataUrl(image), accountId }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Caption generation failed.");
      setCaption(data.caption);
      setNoticeTone("green");
      setNotice("Caption generated by the existing SMMPRO OpenAI connection.");
    } catch (reason) {
      setNoticeTone("red");
      setNotice(reason instanceof Error ? reason.message : "Caption generation failed.");
    } finally {
      setGenerating(false);
    }
  }

  async function publishNow() {
    if (!caption.trim() && !image) {
      setNoticeTone("amber");
      setNotice("Add a caption or image before publishing.");
      return;
    }
    if (!publishFacebook && !publishInstagram) {
      setNoticeTone("amber");
      setNotice("Choose Facebook, Instagram or both.");
      return;
    }
    setPublishing(true);
    setNotice("");
    try {
      const form = new FormData();
      form.append("message", caption);
      form.append("accountId", accountId);
      form.append("publishFacebook", String(publishFacebook));
      form.append("publishInstagram", String(publishInstagram));
      if (image) form.append("image", image);

      const response = await fetch("/api/publish", { method: "POST", body: form });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Publishing failed.");
      sessionStorage.setItem("socio-last-publish", JSON.stringify(data));
      setNoticeTone("green");
      setNotice("Publishing job completed through the SMMPRO Meta connection.");
      await router.push("/publishing/job-1");
    } catch (reason) {
      setNoticeTone("red");
      setNotice(reason instanceof Error ? reason.message : "Publishing failed.");
    } finally {
      setPublishing(false);
    }
  }

  return (
    <Shell
      route="studio"
      title="Creative Studio"
      description="Generate a caption and publish with SMMPRO’s existing Meta and OpenAI connections."
      actions={
        <>
          <Btn
            kind="secondary"
            onClick={() => {
              localStorage.setItem("socio-draft-caption", caption);
              setNoticeTone("green");
              setNotice("Draft saved in this browser.");
            }}
          >
            Save Draft
          </Btn>
          <Btn kind="secondary" onClick={generateCaption} disabled={generating}>
            {generating ? "Generating…" : "Generate Caption"}
          </Btn>
          <Btn onClick={publishNow} disabled={publishing}>
            {publishing ? "Publishing…" : "Publish Now"}
          </Btn>
        </>
      }
    >
      {notice && (
        <div className="mb-5">
          <Notice tone={noticeTone}>{notice}</Notice>
        </div>
      )}
      <div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]">
        <Card className="p-6">
          <h2 className="text-xl font-bold">Post brief</h2>
          <div className="mt-5 grid gap-4 sm:grid-cols-2">
            <label className="block text-sm font-semibold text-slate-700">
              Brand
              <select
                value={accountId}
                onChange={(event) => setAccountId(event.target.value)}
                className="mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100"
              >
                <option value="chezahub">ChezaHub</option>
                <option value="jengasites">JengaSites</option>
              </select>
            </label>
            <Field label="Objective" value="Sales" />
            <Field label="Content pillar" value="Best Region Deal" />
            <Field label="Format" value="Instagram 4:5" />
            <Field label="Product" value="Marvel’s Spider-Man 2 — PS5" />
            <Field label="Best region" value="South Africa" />
            <Field label="Sale price" value="KSh 3,790" />
            <Field label="Headline" value="SAME GAME. BETTER PRICE." />
          </div>
          <label className="mt-5 block cursor-pointer rounded-xl border-2 border-dashed border-slate-200 p-6 text-center hover:border-rose-300">
            <b>{image ? image.name : "Add artwork"}</b>
            <p className="mt-1 text-xs text-slate-500">PNG, JPG or WEBP • Max 10 MB</p>
            <input
              type="file"
              accept="image/png,image/jpeg,image/webp"
              className="sr-only"
              onChange={(event) => chooseImage(event.target.files?.[0] || null)}
            />
          </label>
          <label className="mt-4 block text-sm font-semibold">
            Caption
            <textarea
              aria-label="Post caption"
              className="mt-2 w-full rounded-lg border border-slate-200 p-3 outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100"
              rows={7}
              value={caption}
              onChange={(event) => setCaption(event.target.value)}
            />
          </label>
          <fieldset className="mt-5">
            <legend className="text-sm font-semibold">Publishing targets</legend>
            <div className="mt-2 flex flex-wrap gap-4 text-sm">
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={publishFacebook}
                  onChange={(event) => setPublishFacebook(event.target.checked)}
                />
                Facebook Page
              </label>
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={publishInstagram}
                  onChange={(event) => setPublishInstagram(event.target.checked)}
                />
                Instagram
              </label>
            </div>
          </fieldset>
        </Card>
        <Card className="p-6">
          <div className="mx-auto max-w-md rounded-3xl bg-[#071426] p-8 text-white">
            <p className="text-xs font-semibold">
              {accountId === "chezahub" ? "CHEZAHUB DEAL DROP" : "JENGASITES BUSINESS GROWTH"}
            </p>
            <h2 className="mt-5 text-4xl font-bold">
              SAME GAME.
              <br />
              BETTER PRICE.
            </h2>
            {preview ? (
              <img
                src={preview}
                alt="Selected post artwork preview"
                className="mt-6 aspect-[1.7] w-full rounded-2xl object-cover"
              />
            ) : (
              <div className="mt-6 aspect-[1.7] rounded-2xl bg-slate-700" />
            )}
            <p className="mt-6 text-4xl font-bold">KSh 3,790</p>
            <p className="mt-2 text-sm text-slate-300">
              Was KSh 5,030 • South Africa • PS5
            </p>
            <p className="mt-6 font-bold">SHOP NOW → CHEZAHUB.CO.KE</p>
          </div>
        </Card>
      </div>
    </Shell>
  );
}

export function Approval() {
  const router = useRouter();
  const [comments, setComments] = useState(1);
  const [notice, setNotice] = useState("");
  return (
    <Shell
      route="approvals"
      title="Review: Spider-Man 2 Best Region Deal"
      description="Submitted by Ryan • Version 4 • Due today at 6:30 PM"
      actions={
        <>
          <Btn
            kind="secondary"
            onClick={() => setNotice("Changes requested from Ryan.")}
          >
            Request changes
          </Btn>
          <Btn onClick={() => router.push("/publishing/job-1")}>
            Approve & schedule
          </Btn>
        </>
      }
    >
      {notice && (
        <div className="mb-5">
          <Notice tone="amber">{notice}</Notice>
        </div>
      )}
      <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
        <Card className="p-6">
          <div className="mx-auto max-w-md rounded-2xl bg-[#071426] p-8 text-white">
            <h2 className="text-4xl font-bold">SAME GAME. BETTER PRICE.</h2>
            <div className="mt-6 aspect-video rounded-xl bg-slate-700" />
            <p className="mt-6 text-4xl font-bold">KSh 3,790</p>
          </div>
          <h3 className="mt-6 font-bold">Comments ({comments})</h3>
          <div className="mt-3 rounded-xl bg-slate-50 p-4 text-sm">
            Faith: Can we make the original price more visible?
          </div>
          <Btn
            kind="secondary"
            className="mt-3"
            onClick={() => setComments((current) => current + 1)}
          >
            Add comment
          </Btn>
        </Card>
        <Card className="p-6">
          <h2 className="text-xl font-bold">Approval checklist</h2>
          {[
            "Price current",
            "Region correct",
            "Stock available",
            "Logo protected",
            "Text safe area",
            "Caption matches",
            "CTA tracked",
          ].map((x) => (
            <div
              key={x}
              className="mt-3 flex items-center justify-between rounded-xl bg-slate-50 p-4"
            >
              <span>{x}</span>
              <CheckCircle2 className="text-emerald-600" aria-hidden="true" />
            </div>
          ))}
        </Card>
      </div>
    </Shell>
  );
}
